### ISSUE TITLE
Cannot set fk to int64 when returning the model from a helper proc

### ISSUE THREAD

**Issue by Dankr4d** [moigagoo/norm#42]
When I define the foreign key as int64 and want to write a helper proc that will return the model/object, I'll get the following error. That's because in sqlites rowutils the `to` template does not handle int64 types. I can compile everything successfully when i comment out my helper proc or change the foreign key type to int.
```
normtest.nim(46, 1) template/generic instantiation of `withDb` from here
normtest.nim(49, 24) template/generic instantiation of `getOne` from here
.nimble/pkgs/norm-1.0.17/norm/sqlite.nim(137, 15) template/generic instantiation of `getOne` from here
.nimble/pkgs/norm-1.0.17/norm/sqlite.nim(132, 17) template/generic instantiation of `to` from here
.nimble/pkgs/norm-1.0.17/norm/sqlite/rowutils.nim(129, 9) Error: unreachable statement after 'return' statement or '{.noReturn.}' proc
```

**Comment by moigagoo** [comment]
Thanks for reporting the issue! 

The problem is that there is no built-in handling for int64  type (or int32, uint, or non-standard ints). So, Norm tries to store int64 values as TEXT as you can see by enabling logging:
```
 companyId TEXT NOT NULL DEFAULT '' REFERENCES companies (id),
```
And since there is no built-in parser available for int64 type, Norm doesn`t know how to parse those strings from the DB back to int64:
```
Error: unhandled exception: Parser for int64 is undefined. [ValueError]
```
There are three ways out of this situation:
1. Use int instead of int64. Could you please tell why you want to use int64 in the first place?
2. Provide missing DB information with pragmas:
```
    CompanyEmail {.table: "companyemails".} = object
      companyId {.
        fk: Company,
        dbType: "INTEGER NOT NULL DEFAULT 0",
        parseIt: it.i
      .}: int64 # Crashes when set to int64. Works well when set to int.
      email: string
      enabled {.default: "1", ro.}: bool
```
With this modification, your code compiles and gives the right answer:
```
company: (id: 1, name: "Name", website: "https://nim-lang.org/", enabled: false)
company.emails[0..1]: @[(id: 1, companyId: 1, email: "test@localhost.loc", enabled: false), (id: 2, companyId: 1, email: "test@localhost.loc", enabled: false)]
```
3. Add int64 to built-in supported types. This is very easy to do, but I'd like to learn more about your case first. I.e. why you use int64 and not plain int.

**Comment by moigagoo** [comment]
> I also ask myself why getMany must have a limit? Why is it not an optional parameter?
I remember there was a reason but I cannot remember it anymore :-) Feel free to open an issue (and submit a PR ;-)

**Comment by Dankr4d** [comment]
> 1. Use int instead of int64. Could you please tell why you want to use int64 in the first place?

I read on the sqlite website (https://www.sqlite.org/lang_createtable.html#rowid), that the rowid is stored as int64 and that every primary key defined as an integer (if it's the only primary key) is an alias for the rowid. Thefore the primary key `id` field is stored as int64 in sqlite. So foreign keys should  be also stored as int64 (if I got it right).

From the sqlite website:
> Except for WITHOUT ROWID tables, all rows within SQLite tables have a 64-bit signed integer key that uniquely identifies the row within its table.  

> [...]

> With one exception noted below, if a rowid table has a primary key that consists of a single column and the declared type of that column is "INTEGER" in any mixture of upper and lower case, then the column becomes an alias for the rowid

I solved this problem by setting the db pragmas as you mentioned (but without an default) to the following:
```nim
companyId {.
  fk: Company,
  dbType: "INTEGER NOT NULL",
  parseIt: it.i
.}: int64
```
Please let me know if I misunderstood something.

**Comment by moigagoo** [comment]
@Dankr4d I see. Yes, you are correct, ids are int64, I believe, in SQLite and PostgreSQL. Moreover, the excellent ndb package I'm using for lower-level DB access uses int64 for ids, so I'm explicitly converting it to int.

I just thought it was more convenient to use int. To make it clear: you can safely use int instead of int64 and skip those explicit type definitions. If you're on a 64 bit OS, int is int64. And if you're on a 32 bit OS, you won't meet the limitation of int32 for a pretty long time. So this shouldn't be is not a showstopper for you, just use int and don't worry.

However, I can see how adding built-in support for int64 is a good idea, so I'll to it. So you'll be able to use int or int64 without pragmas.
