### ISSUE TITLE
feedback request for refactoring of macros.hasCustomPragma

### ISSUE THREAD

**Issue by krux02** [moigagoo/norm#46]
I am currently refactoring macros.hasCustomPragma. [Here is the PR](https://github.com/nim-lang/Nim/pull/11526), but when I try to compile tsqlite with that refactoring enabled I get the following error. Can you tell me what could have gone wrong?
```
tests/tsqlite.nim(49, 7) template/generic instantiation of `suite` from here
tests/tsqlite.nim(79, 8) template/generic instantiation of `test` from here
tests/tsqlite.nim(80, 5) template/generic instantiation of `withDb` from here
tests/tsqlite.nim(86, 39) Error: type mismatch: got <typeof(nil)>
but expected one of: 
proc dbValue(v: DbValue): DbValue
  first type mismatch at position: 1
  required type for v: DbValue
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: int | int32 | int64 | uint): DbValue
  first type mismatch at position: 1
  required type for v: int or int32 or int64 or uint
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: float): DbValue
  first type mismatch at position: 1
  required type for v: float
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: string): DbValue
  first type mismatch at position: 1
  required type for v: string
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: DbBlob): DbValue
  first type mismatch at position: 1
  required type for v: DbBlob
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: DbNull): DbValue
  first type mismatch at position: 1
  required type for v: DbNull
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: DateTime): DbValue
  first type mismatch at position: 1
  required type for v: DateTime
  but expression 'nil' is of type: typeof(nil)
proc dbValue[T](v: Option[T]): DbValue
  first type mismatch at position: 1
  required type for v: Option[dbValue.T]
  but expression 'nil' is of type: typeof(nil)
proc dbValue(v: bool): DbValue
  first type mismatch at position: 1
  required type for v: bool
  but expression 'nil' is of type: typeof(nil)
```

**Comment by moigagoo** [comment]
Hello, Arne! Thanks for coming by.

Apparently, this has nothing to do with your refactoring. In the trace, I can see this proc declaration:
```
proc dbValue(v: DbNull): DbValue
  first type mismatch at position: 1
  required type for v: DbNull
  but expression 'nil' is of type: typeof(nil)
```
However, it looks differently [in `ndb`](https://github.com/xzfc/ndb.nim/blob/master/ndb/sqlite.nim#L209):
```
proc dbValue*(v: DbNull|type(nil)): DbValue =
  ## Wrap NULL value.
  ## Caveat: ``dbValue(nil)`` doesn't compile on Nim 0.19.x, see
  ## https://github.com/nim-lang/Nim/pull/9231.
  DbValue(kind: dvkNull)
```
As you can see, `nil` should be handled by this proc.

However, this PR https://github.com/nim-lang/Nim/pull/9231 is referenced in the comment stating `dbValue(nil)` shouldn't compile in Nim 0.19.*. The referenced PR is already merged though, so the issue should be eliminated. Also, I swear it does compile in Nim 0.19.* and 1.0.* otherwise this test wouldn't have passed.

So, I have two hypotheses:
1. Handling of `type(nil)` has been changed in Nim in a way that cancels the mentioned PR.
2. Your refactoring somehow affected handling of `type(nil)`.

In both cases, it's `dbValue(nil)` in ndb that is broken, not Norm itself.

Probably should ask @xzfc's input too.

**Comment by xzfc** [comment]
@krux02 It seems you have an outdated version of `ndb` in your nimble cache. Probably because nimble doesn't update `@#head` versions? Possible fix: `rm -r ~/.nimble; nimble install 'ndb@#head'`.

---

@moigagoo 
> Also, I swear it does compile in Nim 0.19 and 1.0 otherwise this test wouldn't have passed.

Maybe you mean 0.20 and 1.0? The first revision of Norm that mentions `dbValue nil` is 6911b37c17f970314b3e7c67d5b03764bfe377b1 and [it was tested on Nim 0.20.0](https://github.com/moigagoo/norm/blob/6911b37c17f970314b3e7c67d5b03764bfe377b1/Dockerfile#L1).

**Comment by moigagoo** [comment]
@xzfc sure, my bad, I meant 0.20. Thanks for the correction.

**Comment by moigagoo** [comment]
@krux02 could you please try running the tests now, after #47 is merged?

**Comment by krux02** [comment]
I will do tomorrow

**Comment by krux02** [comment]
Thanks for the update. Tests are passing now.
