### ISSUE TITLE
norm/postgres santax error

### ISSUE THREAD

**Issue by LantosTG** [moigagoo/norm#48]
Error: unhandled exception: ERROR:  syntax error at or near "user"
LINE 1: DROP TABLE IF EXISTS user CASCADE

```nim                           ^
import norm/postgres
import logging # Import logging to inspect the generated SQL statements.
import unicode, sugar, options


db("172.17.0.2", "postgres", "123", "postgres"):
    type
        User = object
            age: Positive
            name: string

    proc getUsers(): seq[User] =
        withDb:
            User.getMany(100, cond = "1")


addHandler newConsoleLogger()
withDb:
    # dbConn.exec(sql"""DROP TABLE IF EXISTS "user" CASCADE""")
    # ^ works but v doesn't
    createTables(force = true)


```

Also are you on discord I just have a few questions I'd like to ask

**Comment by moigagoo** [comment]
Hi! Thanks for opening the issue. I'm 99% sure this is because you can't name tables "user" in PostgreSQL. Well, you can, but it must be quoted all the time, and we don't quote table names in Norm (maybe we should?).

Relevant link: https://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql

I am available in the official Nim Telegram channel. Unfortunately, I don't use Discord or IRC. I'm also active on the forum, so you can reach out there.

**Comment by LantosTG** [comment]
ln 142 sqlgen.
```
    result.add sql "DROP TABLE IF EXISTS $# CASCADE" % dbObjRepr.getTable()
```
```
    result.add sql """DROP TABLE IF EXISTS "$#" CASCADE""" % dbObjRepr.getTable()
```
worked but also changing the user name worked so trying to make it work is against pql spec. Thank you for the link.

Okay I was just going to ask if there is plans to include pooling and bulk inserts in this orm? 

bulk edit something like this
```
type
    User2 = object
       age: Positive

let users: seq[User2]
users.add(User(age=2))
users.and(User(age=2))
users.add(User(age=2))
users.save()
```

**Comment by moigagoo** [comment]
I haven't thought about bulk insertion or update but it seems like a fairly easy feature to implement since we have transactions. So, we can just define `insert`, `update`, and `delete` on `seq[T]` which would just wrap a `for` loop in a transaction.

Please open a issue for bulk editing (PR is welcome too).

I'm closing this issue as there's nothing to be done on Norm's part.
